### PR TITLE
secureTextEntry Android fix

### PR DESCRIPTION
**Pull request by MajinJake**

### CODE REVIEW

**Comment by Bist07** [comment]
i see some other instances, where we are passing "true". can we change those as well

**Comment by Bist07** [comment]
image

**Review by Bist07 — COMMENTED** [review]
change other instances as well

**Comment by MajinJake** [comment]
good catch. Changed the other ones but not the .iml file cause idk what that one does

**Review by Bist07 — APPROVED** [review]
Looks good!

**Pull request merged**
